version: "3.9"
services:
#  TODO переписать под нужды бота
#  bot:
#
#    image: tg-config-bot
#    build:
#      context: .
#    env_file:
#      - .env
#    depends_on:
#      db:
#        condition: service_healthy
#    networks:
#      - postgres
#    environment:
#      BOT_TOKEN: ${BOT_TOKEN}
#      PANEL_PORT: ${PANEL_PORT}
#      KEY_PATH: ${KEY_PATH}
#      XUI_USERNAME: ${XUI_USERNAME}
#      XUI_PASSWORD: ${XUI_PASSWORD}
#      POSTGRES_NAME: ${POSTGRES_NAME}
#      POSTGRES_USER: ${POSTGRES_USER}
#      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
#      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
#      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
#      ADMIN_CHATS: ${ADMIN_CHATS}
#    deploy:
#      resources:
#        limits:
#          cpus: '0.5'
#          memory: 512M
#    healthcheck:
#      test: [ "CMD-SHELL", "pgrep -f java || exit 1" ]
#      interval: 10s
#      timeout: 5s
#      retries: 6
#      start_period: 20s

  db:
    image: postgres:latest
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db-data:/var/lib/db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G
    networks:
      - postgres

volumes:
  db-data:
  pgadmin-data:

networks:
  postgres:
    driver: bridge