services:
#  TODO переписать под нужды бота
  bot:
    image: tg-config-bot
    build:
      context: .
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - postgres
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      GERMAN_PANEL_HOME_URL: ${GERMAN_PANEL_HOME_URL}
      LATV_PANEL_HOME_URL: ${LATV_PANEL_HOME_URL}
      XUI_USERNAME: ${XUI_USERNAME}
      XUI_PASSWORD: ${XUI_PASSWORD}
      XUI_PASSWORD_LATV: ${XUI_PASSWORD_LATV}
      XUI_USERNAME_LATV: ${XUI_USERNAME_LATV}
      DB_LINK_PROD: ${DB_LINK_PROD}
      DB_LINK_DEV: ${DB_LINK_DEV}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      ADMIN_CHATS: ${ADMIN_CHATS}
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    healthcheck:
      test: [ "CMD-SHELL", "pgrep -f java || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 6
      start_period: 20s

  db:
    image: postgres:latest
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db-data:/var/lib/db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G
    networks:
      - postgres

volumes:
  db-data:
  pgadmin-data:

networks:
  postgres:
    driver: bridge